# database generated on 2024-10-23 13:48 GMT
!!omap
- /media/saravana/Non-os/ACT_Generated_Tests/Zcmt/RV64/jalt/cm.jalt-01.S:
    commit_id: '-'
    isa:
    - RV64I_Zca_Zcmt
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*Zca.*Zcmt.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - cm.jalt
