# database generated on 2024-10-29 07:39 GMT
!!omap
- /media/saravana/Non-os/ACT_Generated_Tests/Zcmt/RV32/jt/cm.jt-01.S:
    commit_id: '-'
    isa:
    - RV32I_Zca_Zcmt
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*Zca.*Zcmt.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - cm.jt
