# database generated on 2024-10-23 13:22 GMT
!!omap
- /media/saravana/Non-os/ACT_Generated_Tests/Zcmp/RV32/push/cm.push-01.S:
    commit_id: '-'
    isa:
    - RV32I_Zca_Zcmp
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*I.*Zca.*Zcmp.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - cm.push
